spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog_db?serverTimezone=UTC
    username: root
    password: fjj960416
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html




server:
  port: 8888

debug: true

logging:
  level.myblog.*: debug

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
